### ISSUE TITLE
How is a Participant deregistered from PEPPOL Directory?

### ISSUE THREAD

**Issue by clancger** [phax/peppol-directory#5]
If an endpoint is listed in PD, and is deregistered from their original SMP,  will the delete from PD happen automatically, and if so, when?

**Comment by phax** [comment]
Unfortunately the deletion does not happen automatically, because the PD cannot determine between a participant being completely offline and a participant being just temporarily offline.

The recommendation to SMP providers if a service group (the SMP root entity) is deleted, is to also delete the business card in the SMP. If the business card is deleted, the HTTP DELETE request should be send to the PEPPOL Directory. Otherwise the PD has no chance to determine what's going wrong.

Does that clarify your issue?
